# Cloudflare Pages configuration for Easy Hybrid
name = "easy-hybrid"
compatibility_date = "2024-08-01"
pages_build_output_dir = "dist"

[build]
command = "npm run build"

[env.production]
vars = { NODE_ENV = "production" }

[env.preview]
vars = { NODE_ENV = "development" }

# Environment variables for GitHub OAuth
# These should be set in the Cloudflare Pages dashboard
# GITHUB_CLIENT_SECRET = "your_github_client_secret_here"